CREATE TABLE ROOM(
  ROOM_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(16) NOT NULL,
  ROOM_NUMBER VARCHAR(16) NOT NULL UNIQUE,
  BED_INFO VARCHAR(32) NOT NULL,
  STATUS VARCHAR(32) NOT NULL
);