CREATE TABLE if not exists ROOM(
  ROOM_ID BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  NAME VARCHAR(16) NOT NULL,
  ROOM_NUMBER VARCHAR(16) NOT NULL UNIQUE,
  BED_INFO VARCHAR(32) NOT NULL,
  STATUS VARCHAR(32) NOT NULL
);