services:
  atlas-hotel-db:
    container_name: atlas-hotel-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: atlas-hotel
    extends:
      file: base-config.yml
      service: microservice-db-config

  configserver:
    image: "dmslob/config-server:v1"
    container_name: configserver
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent http://localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: base-config.yml
      service: microservice-base-config

  eurekaserver:
    image: "dmslob/eurekaserver:v1"
    container_name: eurekaserver
    ports:
      - "8070:8070"
    healthcheck:
      test: "curl --fail --silent http://localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: base-config.yml
      service: microservice-configserver-config
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"

  guest-service:
    image: "dmslob/guest-service:v1"
    container_name: guest-service
    ports:
      - "8080:8080"
    healthcheck:
      test: "curl --fail --silent http://localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      atlas-hotel-db:
        condition: service_healthy
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "guest-service"
    extends:
      file: base-config.yml
      service: microservice-eureka-config

  room-service:
    image: "dmslob/room-service:v1"
    container_name: room-service
    ports:
      - "8081:8081"
    healthcheck:
      test: "curl --fail --silent http://localhost:8081/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      atlas-hotel-db:
        condition: service_healthy
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "room-service"
    extends:
      file: base-config.yml
      service: microservice-eureka-config

  reservation-service:
    image: "dmslob/reservation-service:v1"
    container_name: reservation-service
    ports:
      - "8082:8082"
    healthcheck:
      test: "curl --fail --silent http://localhost:8082/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      atlas-hotel-db:
        condition: service_healthy
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "reservation-service"
    extends:
      file: base-config.yml
      service: microservice-eureka-config

  gatewayserver:
    image: "dmslob/gatewayserver:v1"
    container_name: gatewayserver
    ports:
      - "8072:8072"
    depends_on:
      guest-service:
        condition: service_healthy
      room-service:
        condition: service_healthy
      reservation-service:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "gatewayserver"
    extends:
      file: base-config.yml
      service: microservice-eureka-config

networks:
  atlas-hotel-network:
    driver: "bridge"