spring:
  application:
    name: guest-service
  profiles:
    active: "default"
  config:
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: "Guest Service"
    description: "A service to manage hotel guests."
    version: "1.0.0"

eureka:
  instance:
    preferIpAddress: true
#    hostname: localhost
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/