
CREATE TABLE if not exists GUEST(
  GUEST_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR(64),
  LAST_NAME VARCHAR(64),
  EMAIL_ADDRESS VARCHAR(64),
  COUNTRY VARCHAR(32),
  PHONE_NUMBER VARCHAR(24),
  REGISTERED_AT TIMESTAMP
);