spring:
  application:
    name: reservation-service
  profiles:
    active: "default"
  config:
    import: "optional:configserver:http://localhost:8071/"
# refreshing props at runtime
management:
  endpoints:
    web:
      exposure:
        include: "*"
