CREATE TABLE RESERVATION(
  RESERVATION_ID BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  GUEST_ID BIGINT NOT NULL,
  ROOM_ID BIGINT NOT NULL,
  DATE_IN TIMESTAMP,
  DATE_OUT TIMESTAMP,
  STATUS VARCHAR(20)
);