# For externalized configuration in a distributed system.
guests:
  message: "Hello, Guest!"

info:
  app:
    name: "Guest Service"
    description: "A service to manage hotel guests."
    version: "1.0.0"
