# For externalized configuration in a distributed system.
reservations:
  message: "Hello, reservations!"

info:
  app:
    name: "Reservation Service"
    description: "A service to manage hotel reservations."
    version: "1.0.0"